---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
    register: stat_result
  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url:  http://3.128.87.109:8081/service/rest/v1/search/assets/download?sort=version&repository=maven-releases&maven.groupId=com.geekcap.vmturbo&maven.artifactId=hello-world-servlet-example&maven.baseVersion=artifactversion&maven.extension=war
       dest: /usr/share/tomcat/webapps/hello-world-servlet-example.war
       mode: 0700
  - name: Start Tomcat
    service: name=tomcat state=started
